# name: Deploy to PROD
# "on":
#     push:
#         branches:
#             - main
# jobs:
#     build_and_deploy:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v4
#             - run: npm i
#             - run: npm install -g @angular/cli@latest
#             - run: ng build
#             - uses: FirebaseExtended/actions-hosting-deploy@v0
#               with:
#                 repoToken: ${{ secrets.GITHUB_TOKEN }}
#                 firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRODUCT_STORE }}
#                 chanelId:
#                 projectId: 'product-store-d1c19'
#                 target: 'product-store-d1c19'
